name: Callable Workflow
on:
  workflow_call:
    inputs:
      boolean:
        type: boolean
        description: test boolean
        required: false
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Show me the money!
        shell: bash
        run: | 
          echo test inputs value: ${{ inputs.boolean == undefined}} ${{ inputs.boolean == null }} ${{ inputs.boolean != undefined }} ${{ inputs.boolean != null }}
          echo complex: ${{ github.event.inputs.boolean || inputs.boolean == null && ('last option') || inputs.boolean }}
          echo boolean: ${{ github.event.inputs.boolean == true || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          echo string: "${{ github.event.inputs.string || 'default' }}"



          

