name: Callable Workflow
on:
  workflow_call:
    inputs:
      boolean:
        type: boolean
        description: test boolean
        required: false
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Show me the money!
        shell: bash
        run: | 
          echo inputs.boolean: ${{ inputs.boolean != null && inputs.boolean || 'null' }}
          echo test complex: ${{ github.event.inputs.apply == true || ${{ inputs.boolean != null && inputs.boolean || 'unset' }} != 'unset' || 'last option' }}
          echo boolean: ${{ github.event.inputs.boolean == true || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          echo string: "${{ github.event.inputs.string || 'default' }}"

          

