name: Callable Workflow
on:
  workflow_call:
    inputs:
      boolean:
        type: boolean
        description: test boolean
        required: false
      apply:
        type: string
        description: "'true' for apply, 'false' for don't apply"
        required: false
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Show me the money!
        shell: bash
        run: | 
          echo test inputs value: ${{ inputs.boolean == null }} ${{ inputs.boolean != null }}
          echo input: ${{ inputs.boolean }} ${{ inputs.boolean == null }}
          echo complex: ${{ github.event.inputs.boolean || inputs.boolean == null && ('last option') || inputs.boolean }}
          echo boolean: ${{ github.event.inputs.boolean == true || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          echo string: "${{ github.event.inputs.string || 'default' }}"

          echo == null \t\t${{ inputs.boolean == null }}
          echo == false \t\t${{ inputs.boolean == false }}
          echo == true \t\t${{ inputs.boolean == true }}
          echo == \'false\' \t${{ inputs.boolean == 'false' }}
          echo == \'true\' \t\t${{ inputs.boolean == 'true' }}

          echo == null ${{ github.event.inputs.boolean == null }}
          echo == false ${{ github.event.inputs.boolean == false }}
          echo == true ${{ github.event.inputs.boolean == true }}
          echo == \'false\' ${{ github.event.inputs.boolean == 'false' }}
          echo == \'true\' ${{ github.event.inputs.boolean == 'true' }}



          
# dispatched bool unchecked:
# == null     false
# == false    false
# == true     false
# == 'false'  true
# == 'true'   false

# dispatched bool checked:
# == null     false
# == false    false
# == true     false
# == 'false'  false
# == 'true'   true

# input bool unset
# == null     true
# == false    true
# == true     false
# == 'false'  false
# == 'true'   false

# input bool false
# == null     true
# == false    true
# == true     false
# == 'false'  false
# == 'true'   false