name: Test
"on":
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      boolean:
        description: Boolean test input
        required: false
        type: boolean
      string:
        description: String test input
        default: test-foo
        required: false
        type: string
jobs:
  workspace:
    name: Call workflow
    uses: ./.github/workflows/callable.yml
    with:
      boolean: false

